### ISSUE TITLE
Compilation failed due to modules not found

### ISSUE THREAD

**Issue by JayJay1024** [darwinia-network/indexer#59]
```bash
~/source-code/subql/indexer/subql on  main ⌚ 19:34:53
$ yarn build:mmr -- pangolin
yarn run v1.22.0
warning From Yarn 1.0 onwards, scripts don't require "--" for options to be forwarded. In a future version, any explicit "--" will be forwarded as-is to the scripts.
$ cd packages/mmr && npm run build pangolin

> subql-mmr@0.0.1 build
> node ../../scripts/build.js mmr "pangolin"

[build] [env] wrote env to /Users/lauyearh/source-code/subql/indexer/subql/packages/mmr/src/_env.ts
[build] ENV DATA:  {
  "CHAIN": "pangolin"
}
[build] [schema] merge schema to /Users/lauyearh/source-code/subql/indexer/subql/packages/mmr/schema.graphql from /Users/lauyearh/source-code/subql/indexer/subql/packages/mmr/schema/generic/schema.graphql
[build] [schema] merge schema to /Users/lauyearh/source-code/subql/indexer/subql/packages/mmr/schema.graphql from /Users/lauyearh/source-code/subql/indexer/subql/packages/mmr/schema/mmr/schema.graphql
[build] [schema] all schemas merged
[build] [chaintypes] copy chaintypes from /Users/lauyearh/source-code/subql/indexer/subql/chaintypes to /Users/lauyearh/source-code/subql/indexer/subql/packages/mmr/chaintypes
[build] [codegen] prepare generate schema types
@polkadot/util has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
        cjs 8.7.1       node_modules/@polkadot/util
        cjs 9.7.2       node_modules/@subql/utils/node_modules/@polkadot/util/cjs
===============================
---------Subql Codegen---------
===============================
* Schema Block generated !
* Schema MMRNodeEntity generated !
* Models index generated !
* Types index generated !
[build] [codegen] generated schema types
[build] [codebuild] prepare build project
../../node_modules/@subql/types/dist/interfaces.d.ts:1:33 - error TS2307: Cannot find module '@polkadot/types-codec/types' or its corresponding type declarations.

1 import { AnyTuple, Codec } from '@polkadot/types-codec/types';
                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

../../node_modules/@subql/types/dist/interfaces.d.ts:2:34 - error TS2307: Cannot find module '@polkadot/types/extrinsic' or its corresponding type declarations.

2 import { GenericExtrinsic } from '@polkadot/types/extrinsic';
                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~

../../node_modules/@subql/types/dist/interfaces.d.ts:3:42 - error TS2307: Cannot find module '@polkadot/types/interfaces' or its corresponding type declarations.

3 import { EventRecord, SignedBlock } from '@polkadot/types/interfaces';
                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

../../node_modules/@subql/types/dist/interfaces.d.ts:4:24 - error TS2307: Cannot find module '@polkadot/types/types' or its corresponding type declarations.

4 import { IEvent } from '@polkadot/types/types';
                         ~~~~~~~~~~~~~~~~~~~~~~~

../../node_modules/@subql/types/dist/project.d.ts:1:28 - error TS2307: Cannot find module '@polkadot/api' or its corresponding type declarations.

1 import { ApiPromise } from '@polkadot/api';
                             ~~~~~~~~~~~~~~~

../../node_modules/@subql/types/dist/project.d.ts:2:41 - error TS2307: Cannot find module '@polkadot/types/types' or its corresponding type declarations.

2 import { AnyTuple, RegistryTypes } from '@polkadot/types/types';
                                          ~~~~~~~~~~~~~~~~~~~~~~~

src/handler/chain/basic.ts:1:65 - error TS2307: Cannot find module 'index-common' or its corresponding type declarations.

1 import {FastBlock, FastEvent, FastExtrinsic, IndexHandler} from "index-common";
                                                                  ~~~~~~~~~~~~~~

src/handler/chain/basic.ts:25:9 - error TS2304: Cannot find name 'logger'.

25         logger.error(`Failed to handle block when call ${handler.name()} handler: ${e}`);
           ~~~~~~

src/handler/chain/basic.ts:35:9 - error TS2304: Cannot find name 'logger'.

35         logger.error(`Failed to handle event when call ${handler.name()} handler: ${e}`);
           ~~~~~~

src/handler/chain/basic.ts:45:9 - error TS2304: Cannot find name 'logger'.

45         logger.error(`Failed to handle call when call ${handler.name()} handler: ${e}`);
           ~~~~~~

src/types/models/Block.ts:31:15 - error TS2304: Cannot find name 'store'.

31         await store.set('Block', id.toString(), this);
                 ~~~~~

src/types/models/Block.ts:35:15 - error TS2304: Cannot find name 'store'.

35         await store.remove('Block', id.toString());
                 ~~~~~

src/types/models/Block.ts:40:30 - error TS2304: Cannot find name 'store'.

40         const record = await store.get('Block', id.toString());
                                ~~~~~

src/types/models/MMRNodeEntity.ts:27:15 - error TS2304: Cannot find name 'store'.

27         await store.set('MMRNodeEntity', id.toString(), this);
                 ~~~~~

src/types/models/MMRNodeEntity.ts:31:15 - error TS2304: Cannot find name 'store'.

31         await store.remove('MMRNodeEntity', id.toString());
                 ~~~~~

src/types/models/MMRNodeEntity.ts:36:30 - error TS2304: Cannot find name 'store'.

36         const record = await store.get('MMRNodeEntity', id.toString());
                                ~~~~~

src/handler/logic/mmr/helpers.ts:1:42 - error TS2307: Cannot find module '@polkadot/types' or its corresponding type declarations.

1 import { TypeRegistry, Raw, Tuple } from "@polkadot/types";
                                           ~~~~~~~~~~~~~~~~~

src/handler/logic/mmr/helpers.ts:3:29 - error TS2307: Cannot find module '@polkadot/util-crypto' or its corresponding type declarations.

3 import { blake2AsHex } from "@polkadot/util-crypto";
                              ~~~~~~~~~~~~~~~~~~~~~~~

src/handler/chain/impls.ts:2:35 - error TS2307: Cannot find module 'index-common' or its corresponding type declarations.

2 import {Chain, IndexHandler} from "index-common";
                                    ~~~~~~~~~~~~~~

src/mappings/mappingHandlers.ts:2:85 - error TS2307: Cannot find module 'index-common' or its corresponding type declarations.

2 import {activeChain, Chain, FastBlock, FastEvent, FastExtrinsic, IndexHandler} from "index-common";
                                                                                      ~~~~~~~~~~~~~~

src/mappings/mappingHandlers.ts:14:5 - error TS2304: Cannot find name 'logger'.

14     logger.error(`Can not read active chain: ${e.message || 'No message'}`, e);
       ~~~~~~

src/mappings/mappingHandlers.ts:29:7 - error TS2304: Cannot find name 'logger'.

29       logger.warn(`Can not support current chain: ${chain}`);
         ~~~~~~


Found 22 errors.

node:child_process:747
    throw err;
    ^

Error: Command failed: npx tsc -b
    at checkExecSyncError (node:child_process:707:11)
    at Object.execSync (node:child_process:744:15)
    at buildProject (/Users/lauyearh/source-code/subql/indexer/subql/scripts/build.js:111:18)
    at main (/Users/lauyearh/source-code/subql/indexer/subql/scripts/build.js:142:3)
    at Object.<anonymous> (/Users/lauyearh/source-code/subql/indexer/subql/scripts/build.js:145:1)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 13519,
  stdout: null,
  stderr: null
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by JayJay1024** [comment]
Maybe the install command should be run first? But it fails when running the install command

```bash
~/source-code/subql/indexer/subql/packages/mmr on  main ⌚ 19:46:16
$ yarn install
yarn install v1.22.0
info No lockfile found.
[1/4] 🔍  Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/index-common: Not found".
info If you think this is a bug, please open a bug report with the information provided in "/Users/lauyearh/source-code/subql/indexer/subql/packages/mmr/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by JayJay1024** [comment]
```bash
$ cd indexer/subql
$ npm i
$ npx lerna bootstra
$ npm run build:common
$ npm run build:apps -- pangolin
```
