### ISSUE TITLE
Failed to build subql

### ISSUE THREAD

**Issue by JayJay1024** [darwinia-network/indexer#90]
Cmd:

```bash
cd indexer/subql
npm i
npx lerna bootstrap
npm run build:common
npm run build:apps -- pangolin
```

Output:

```bash
$ npm run build:apps -- pangolin

> subql@0.0.1 build:apps
> cd packages/apps && npm run build "pangolin"


> subql-apps@0.0.1 build
> node ../../scripts/build.js apps "pangolin"

[build] [env] wrote env to /Users/lauyearh/source-code/subql/indexer/subql/packages/apps/src/_env.ts
[build] ENV DATA:  {
  "CHAIN": "pangolin"
}
[build] [schema] merge schema to /Users/lauyearh/source-code/subql/indexer/subql/packages/apps/schema.graphql from /Users/lauyearh/source-code/subql/indexer/subql/packages/apps/schema/generic/schema.graphql
[build] [schema] merge schema to /Users/lauyearh/source-code/subql/indexer/subql/packages/apps/schema.graphql from /Users/lauyearh/source-code/subql/indexer/subql/packages/apps/schema/feemarket/schema.graphql
[build] [schema] merge schema to /Users/lauyearh/source-code/subql/indexer/subql/packages/apps/schema.graphql from /Users/lauyearh/source-code/subql/indexer/subql/packages/apps/schema/staking/schema.graphql
[build] [schema] all schemas merged
[build] [chaintypes] copy chaintypes from /Users/lauyearh/source-code/subql/indexer/subql/chaintypes to /Users/lauyearh/source-code/subql/indexer/subql/packages/apps/chaintypes
[build] [codegen] prepare generate schema types
@polkadot/util has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
	cjs 10.1.11	node_modules/@polkadot/util/cjs
	cjs 9.7.2  	node_modules/@subql/utils/node_modules/@polkadot/util/cjs
===============================
---------Subql Codegen---------
===============================
* Schema Block generated !
* Schema QuoteHistory generated !
* Schema FeeHistory generated !
* Schema Reward generated !
* Schema Slash generated !
* Schema Market generated !
* Schema Relayer generated !
* Schema Order generated !
* Schema OrderRelayer generated !
* Schema StakingStash generated !
* Schema StakingRewarded generated !
* Models index generated !
* Types index generated !
[build] [codegen] generated schema types
[build] [codebuild] prepare build project
node_modules/@darwinia/index-common/dist/types/extrinsic.d.ts:8:42 - error TS2694: Namespace '"/Users/lauyearh/source-code/subql/indexer/subql/packages/apps/node_modules/@subql/types/dist/index"' has no exported member 'TypedEventRecord'.

8     get events(): import("@subql/types").TypedEventRecord<import("@polkadot/types-codec/types").Codec[]>[];
                                           ~~~~~~~~~~~~~~~~


Found 1 error.

node:child_process:902
    throw err;
    ^

Error: Command failed: npx tsc -b
    at checkExecSyncError (node:child_process:828:11)
    at Object.execSync (node:child_process:899:15)
    at buildProject (/Users/lauyearh/source-code/subql/indexer/subql/scripts/build.js:111:18)
    at main (/Users/lauyearh/source-code/subql/indexer/subql/scripts/build.js:142:3)
    at Object.<anonymous> (/Users/lauyearh/source-code/subql/indexer/subql/scripts/build.js:145:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 85938,
  stdout: null,
  stderr: null
}

~/source-code/subql/indexer/subql on  fee-market-parachain! ⌚ 19:29:21
```

The same error when build bridger (`npm run build:bridger -- crab`)

**Comment by JayJay1024** [comment]
The compiled code is not the same

<img width="904" alt="image" src="https://user-images.githubusercontent.com/21007682/196041336-3dde31cc-0ea0-494f-a0b9-eae9242a3072.png">

<img width="889" alt="image" src="https://user-images.githubusercontent.com/21007682/196041383-99c926be-2a24-4477-8cb8-dcd22b7f8794.png">

**Comment by JayJay1024** [comment]
We shouldn't both ignore `yarn.lock` and `package-lock.json`, one of these lock files should add to git
